### ISSUE TITLE
Game Stuck when Eternal Tag tries to add Eternal Sticker to an Eternal Joker

### ISSUE THREAD

**Issue by Gaiall** [Firch/Bunco#43] opened 2024-10-26 04:05 UTC
Just beat the boss that gives you an Eternal Tag, and when rerolling in the shop to trigger it so as to not get stuck with it, the game just stays stuck after the reroll.
I cannot hover anything or click on anything and the only option is to start another run. I tried to exit the game to go back to a previous state but it did not work.
I tried to use debug mode to do anything about it but it also prevents the debug menu from opening.

I'm 100% positive the problem is the Eternal Tag, since when replacing the Eternal Tag `apply` function with `return true` the game does not get stuck

**Comment by Gaiall** [comment] 2024-10-26 04:06
![image](https://github.com/user-attachments/assets/fd19fd6c-6d91-4818-b619-2f78016ee063)
 Here's a screenshot of the situation in the shop. The only joker has the Eternal Tag already and the game is stuck

**Comment by dathide** [comment] 2024-11-04 06:37
I have the same issue and Bunco is the only mod I have installed.
![Screenshot_20241103_233453](https://github.com/user-attachments/assets/718ef4b8-d88c-4cc3-b40e-a671e685b606)
[lovely-2024.11.03-23.32.31.log](https://github.com/user-attachments/files/17614462/lovely-2024.11.03-23.32.31.log)

**Comment by dathide** [comment] 2024-11-06 17:20
I circumvented the issue by editing my save.jkr on https://balatro.shorty.systems/
I clicked "Raw", Ctrl+F to find  "tag_bunc_eternal", and removed the section called "tags" with "tag_bunc_eternal" in it.

**Comment by Firch** [comment] 2024-12-07 22:04
Fixed in https://github.com/Firch/Bunco/commit/d93141c05251053821e69f67d2c3874da3ac29dd (also technically a duplicate of https://github.com/Firch/Bunco/issues/39)

**Closed by Firch** 2024-12-07 22:04 UTC
